django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/urls.py
from django.views.generic import TemplateView
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.mainpage, name="mainpage"),
    url(r'^intro/$', views.introduction, name="introduction"),
    url(r'^dataimport/$', views.dataimport, name="dataimport"),
    url(r'^data_confirm/(?P<pk>\d+)/$', views.data_confirm, name="data_confirm"),
    url(r'^data_process/(?P<pk>\d+)/$', views.data_process, name="data_process"),
    url(r'^data_summary/(?P<pk>\d+)/$', views.data_summary, name="data_summary"),
    url(r'^data_reassessment1/(?P<pk>\d+)/$', views.data_reassessment1, name="data_reassessment1"),
    url(r'^data_reassessment2/(?P<pk>\d+)/$', views.data_reassessment2, name="data_reassessment2"),
    url(r'^final_result/(?P<pk>\d+)/$', views.final_result, name="final_result"),
    url(r'^export_delete/(?P<pk>\d+)/$', views.export_delete, name="export_delete"),
    url(r'^contact_us/', TemplateView.as_view(template_name="calcmain/contact_us.html"), name='contact_us'),
    url(r'^mail_complete/', TemplateView.as_view(template_name="calcmain/mail_complete.html"), name='mail_complete'),
]

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/snucalc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('calcmain.urls', namespace='calcmain')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/models.py
from django.db import models
from django.utils import timezone
from picklefield.fields import PickledObjectField


class StudyAnalysis(models.Model):
    study_name = models.CharField(max_length=200)
    treatment_name = models.CharField(max_length=200)
    imported_sheet = models.FileField(upload_to='files/imported_sheets')
    up_patients = models.IntegerField()
    processed_df = PickledObjectField(default="None")
    sorted_df = PickledObjectField(default="None")
    reassessed_df = PickledObjectField(default="None")
    createdAt = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.study_name


class ProbExcelSheets(models.Model):
    sheets_name = models.CharField(max_length=200)
    imported_sheet = models.FileField(upload_to='files/prob_excel_sheets')

    def __str__(self):
        return self.sheets_name

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/forms.py
from django import forms
from .models import StudyAnalysis


class SheetUploadForm(forms.ModelForm):

    class Meta:
        model = StudyAnalysis
        fields = ('study_name', 'treatment_name', 'imported_sheet', 'up_patients')

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .forms import SheetUploadForm
from .models import StudyAnalysis, ProbExcelSheets
import re
import math
import pandas as pd
import numpy as np
from bokeh.charts import Bar, Histogram  # defaults, output_file, show
from bokeh.models import Range1d, Span, Label, BoxAnnotation
from bokeh.embed import components


def mainpage(request):
    return render(request, "calcmain/mainpage.html", {})


def introduction(request):
    return render(request, "calcmain/introduction.html", {})


def dataimport(request):
    if request.method == "POST":
        form = SheetUploadForm(request.POST, request.FILES)
        if form.is_valid():
            study = form.save(commit=False)
            study.createdAt = timezone.now()
            study.save()
            return redirect('calcmain:data_confirm', pk=study.pk)
    else:
        form = SheetUploadForm()
    context = {'form': form}
    return render(request, "calcmain/dataimport.html", context)


def data_confirm(request, pk):
    study = get_object_or_404(StudyAnalysis, pk=pk)
    up_patients = study.up_patients
    main_df = pd.read_excel(study.imported_sheet, sheetname=0)
    num_patients_imported = len(main_df.ID.unique())
    num_all_patients = num_patients_imported + up_patients

    context = {
        "study": study,
        "num_patients_imported": num_patients_imported,
        "num_all_patients": num_all_patients
    }
    return render(request, "calcmain/data_confirm.html", context)


def data_process(request, pk):
    study = get_object_or_404(StudyAnalysis, pk=pk)
    main_df = pd.read_excel(study.imported_sheet, sheetname=0)

    # Change column names and change uppercase characters(organ) into lowercase
    main_df.columns = ['ID', 'Organ', 'Lesion size at baseline (mm)', 'Lesion size at post-treatment (mm)']
    main_df["Organ"] = main_df["Organ"].str.lower()

    # Generate a dataframe for processing the data
    process_df = pd.DataFrame({'Patient ID': list(set([int(i) for i in main_df.ID]))})
    process_df.loc[:, "Number of solid organ tumor"] = 0
    process_df.loc[:, "Number of lymph node"] = 0
    process_df.loc[:, "Tumor burden at the baseline (mm)"] = 0  # Sum of all lesion size at baseline per patient(ID)
    process_df.loc[:, "Tumor burden at the post-treatment (mm)"] = 0 # Sum of all lesion size at post-treatment per patient(ID)
    process_df.loc[:, "Lesion size at the baseline (mm)"] = np.nan # For checking patients who have only one lesion (Solid or Lymph)
    process_df.loc[:, "Percent change (%)"] = 0

    # Check records and update cells
    for record in range(len(main_df.index)):
        record_id = main_df.iloc[:, 0][record]
        lesion_name = main_df.iloc[:, 1][record]
        input_id = record_id - 1

        if re.match("lymph*", lesion_name):
            process_df.loc[input_id, "Number of lymph node"] += 1
        else:
            process_df.loc[input_id, "Number of solid organ tumor"] += 1
        process_df.loc[input_id, "Tumor burden at the baseline (mm)"] += main_df.iloc[:, 2][record]
        process_df.loc[input_id, "Tumor burden at the post-treatment (mm)"] += main_df.iloc[:, 3][record]


    process_df.loc[:, "Number of solid organ tumor"] = process_df.loc[:, "Number of solid organ tumor"].astype(int)
    process_df.loc[:, "Number of lymph node"] = process_df.loc[:, "Number of lymph node"].astype(int)
    process_df.loc[:, "Tumor burden at the baseline (mm)"] = process_df.loc[:, "Tumor burden at the baseline (mm)"].astype(int)
    process_df.loc[:, "Tumor burden at the post-treatment (mm)"] = process_df.loc[:, "Tumor burden at the post-treatment (mm)"].astype(int)

    # Check processed dataframe and update cells
    for record in range(len(process_df.index)):
        process_df.loc[record, 'Percent change (%)'] = math.floor((process_df.loc[record, "Tumor burden at the post-treatment (mm)"] - process_df.loc[record, "Tumor burden at the baseline (mm)"]) / process_df.loc[record, "Tumor burden at the baseline (mm)"] * 100)
        if process_df.loc[record, "Number of lymph node"] + process_df.loc[record, "Number of solid organ tumor"] == 1:
            process_df.loc[record, "Lesion size at the baseline (mm)"] = int(main_df.loc[main_df['ID'] == record + 1]['Lesion size at baseline (mm)'])

    study.processed_df = process_df
    study.save()

    context = {
        "study": study,
        "data": process_df.to_html(
            columns=['Patient ID', 'Number of solid organ tumor', 'Number of lymph node', 'Percent change (%)', 'Tumor burden at the baseline (mm)', 'Tumor burden at the post-treatment (mm)'],
            index=False, na_rep="", bold_rows=True, classes=["table", "table-hover", "table-processed"])
    }
    return render(request, "calcmain/data_processed.html", context)


def data_summary(request, pk):

    study = get_object_or_404(StudyAnalysis, pk=pk)
    processed_df = study.processed_df
    up_patients = study.up_patients
    num_all_patients = len(processed_df.index) + up_patients

    # Calculate the proportions of patients based on diagnosis results.
    num_partial_response = num_progression = 0
    for id in range(len(processed_df.index)):
        if processed_df.loc[:, "Percent change (%)"][id] <= -30:
            num_partial_response += 1
        elif processed_df.loc[:, "Percent change (%)"][id] >= 20:
            num_progression += 1

    partial_response_prop = round(num_partial_response / num_all_patients * 100, 2)
    progression_prop = round((num_progression + up_patients) / num_all_patients * 100, 2)

    # Draw a plot for visualizing patients' diagnosis results.
    new_data = {'Index': [i + 1 for i in range(len(processed_df.index))],
               'Percent change (%)': sorted(processed_df.loc[:, "Percent change (%)"], reverse=True)}
    sorted_df = pd.DataFrame(new_data)

    study.sorted_df = sorted_df
    study.save()

    sorted_plot = Bar(sorted_df, values='Percent change (%)', color="White", title='Percent change (%)', legend=None, ylabel="", ygrid=False)
    sorted_plot.y_range = Range1d(-100, 100)
    sorted_plot.xaxis.visible = False
    sorted_plot.title.text_font = "Roboto Slab"
    sorted_plot.background_fill_alpha = 0
    sorted_plot.border_fill_color = None
    sorted_plot.width = 600    # default : 600
    sorted_plot.height = 250    # default : 600

    line_pr = Span(location=-30, dimension='width', line_color='blue', line_alpha=0.4, line_dash='solid', line_width=2,)
    line_pro = Span(location=20, dimension='width', line_color='red', line_alpha=0.4, line_dash='solid', line_width=2,)
    sorted_plot.add_layout(line_pr)
    sorted_plot.add_layout(line_pro)

    # line-only : x=400, y=135
    citation_pr = Label(x=250, y=170, x_units='screen', y_units='screen',
                     text='Progression (+20%)', text_color='red', text_alpha=0.4, render_mode='css',)
    # line-only : x=375, y=80
    citation_pro = Label(x=235, y=30, x_units='screen', y_units='screen',
                     text='Partial response (-30%)', text_color='blue', text_alpha=0.4, render_mode='css',)
    sorted_plot.add_layout(citation_pr)
    sorted_plot.add_layout(citation_pro)

    pr_box = BoxAnnotation(top=-30, fill_alpha=0.1, fill_color='blue')
    pro_box = BoxAnnotation(bottom=20, fill_alpha=0.1, fill_color='red')
    sorted_plot.add_layout(pr_box)
    sorted_plot.add_layout(pro_box)

    script, div = components(sorted_plot)

    context = {
        "study": study,
        "num_all_patients": num_all_patients,
        "partial_response_prop": partial_response_prop,
        "progression_prop": progression_prop,
        "script": script,
        "div": div
    }
    return render(request, "calcmain/data_summary.html", context)


# Calculate the intra-observer measurement error
def data_reassessment1(request, pk):
    study = get_object_or_404(StudyAnalysis, pk=pk)

    # 1-1) Load probability excel files
    Intra_PR_Multiple = get_object_or_404(ProbExcelSheets, sheets_name="Intra_PR_Multiple")
    Intra_PR_Singular = get_object_or_404(ProbExcelSheets, sheets_name="Intra_PR_Singular")
    Intra_Pro_Multiple = get_object_or_404(ProbExcelSheets, sheets_name="Intra_Pro_Multiple")
    Intra_Pro_Singular = get_object_or_404(ProbExcelSheets, sheets_name="Intra_Pro_Singular")
    PR_Multiple = pd.read_excel(Intra_PR_Multiple.imported_sheet, sheetname=0)
    PR_Singular = pd.read_excel(Intra_PR_Singular.imported_sheet, sheetname=0)
    Pro_Multiple = pd.read_excel(Intra_Pro_Multiple.imported_sheet, sheetname=0)
    Pro_Singular = pd.read_excel(Intra_Pro_Singular.imported_sheet, sheetname=0)

    # 1-2) Change the index of probability dataframe
    def change_index(pd_input):
        pd_input.loc[:, 'PercentChange'] = np.round(pd_input.loc[:, 'PercentChange'])
        pd_input.loc[:, 'PercentChange'] = pd_input.loc[:, 'PercentChange'].astype(int)
        pd_input = pd_input.set_index(['PercentChange'])
        pd_input.columns = pd_input.columns.astype(str)
        return pd_input
    PR_Multiple = change_index(PR_Multiple)
    PR_Singular = change_index(PR_Singular)
    Pro_Multiple = change_index(Pro_Multiple)
    Pro_Singular = change_index(Pro_Singular)

    # 2-1) Prepare the new dataframe about reassessment result (PartialResponse, Progression)
    processed_df = study.processed_df[['Patient ID', 'Number of solid organ tumor', 'Number of lymph node', 'Lesion size at the baseline (mm)', 'Percent change (%)']]
    processed_df.columns = ['ID', 'NS', 'NL', 'LS', 'PC']

    processed_df.loc[:, 'NS'] = processed_df.loc[:, 'NS'].astype(str)
    processed_df.loc[:, 'NL'] = processed_df.loc[:, 'NL'].astype(str)
    processed_df.loc[:, 'LS'] = processed_df.loc[:, 'LS'].astype(str)

    # 2-2) Setting the serial number to each record
    for record in range(len(processed_df.index)):
        if processed_df.loc[record, 'LS'] != 'nan':

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/templates/calcmain/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Measurement variability calculator (RECIST 1.1)</title>

    <!-- Import Google Fonts -->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">

    <!-- Import Bootstrap css files -->
    <link href="{% static 'calcmain/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'calcmain/css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- Import Bokeh css files -->
    <link href="{% static 'calcmain/css/bokeh-0.12.4.min.css' %}" rel="stylesheet">

    <!-- Import Custom css files -->
    <link href="{% static 'calcmain/css/style.css' %}" rel="stylesheet">

    <!-- Apply favicon files -->
    <link rel="shortcut icon" href="{% static 'calcmain/images/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="36x36"  href="{% static 'calcmain/images/android-icon-36x36.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'calcmain/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'calcmain/images/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'calcmain/images/favicon-16x16.png' %}">
</head>


<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" style="width: 100%;">
                <a class="navbar-brand" href="/" style="font-weight: 600;">Measurement variability calculator (RECIST 1.1)</a>
                <span class="navbar-brand navbar-overlay" id="open_nav">&#9776; Contact us</span>
            </div>
        </div>
    </nav>


    {% block content %}
    {% endblock %}


    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <p class="text-muted">Measurement variability calculator (RECIST 1.1)</p>
        </div>
    </footer>


    <!-- The overlay contact form using [ https://formspree.io/ ]-->
    <div id="myNav" class="overlay">
      <!-- Button to close the overlay navigation -->
      <a href="javascript:void(0)" class="closebtn" id="close_nav">&times;</a>
      <!-- Overlay content -->
      <div class="overlay-content div-aligncenter div-centered" style="margin-top: 3%;">
        <iframe id="contact_us" src="{% url 'calcmain:contact_us' %}" height="100%" width="100%" style="border: none;"></iframe>
      </div>
    </div>


    <!-- for ContactUs on navbar -->
    <script>
    document.getElementById('open_nav').onclick = function() {
        document.getElementById("myNav").style.height = "100%";
    }
    document.getElementById('close_nav').onclick = function() {
        document.getElementById("myNav").style.height = "0%";
        setTimeout(function(){
            document.getElementById('contact_us').src = document.getElementById('contact_us').src
        }, 500);
    }
    </script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'calcmain/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'calcmain/js/bokeh-0.12.4.min.js' %}"></script>

    <!-- JS files for overlay loading animations -->
    <script src="{% static 'calcmain/js/jquery-3.1.1.min-loading.js' %}"></script>
    <script src="{% static 'calcmain/js/loadingoverlay.min.js' %}"></script>
    <script src="{% static 'calcmain/js/loadingoverlay_progress.min.js' %}"></script>
    <script src="{% static 'calcmain/js/demo-loading.js' %}"></script>

</body>

</html>

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/templates/calcmain/data_confirm.html
{% extends 'calcmain/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">

    <div class="title text-center">
        <h1 class="title title-introduction">Confirm the data</h1>

        <table class="table table-hover table-main">
            <tr>
                <td style="width: 55%;">Study name</td>
                <td><b>{{ study.study_name }}</b></td>
            </tr>
            <tr>
                <td style="width: 55%;">Treatment name</td>
                <td><b>{{ study.treatment_name }}</b></td>
            </tr>
            <tr>
                <td style="width: 55%;">Number of patients <b>in imported data</b> (A)</td>
                <td><b>{{ num_patients_imported }}</b></td>
            </tr>
            <tr>
                <td style="width: 55%;">Number of enrolled patients <br><b>having unequivocal radiologic progression, symptomatic progression or death </b>(B)</td>
                <td><b>{{ study.up_patients }}</b></td>
            </tr>
            <tr>
                <td style="width: 55%;">Number of <b>enrolled</b> patients (A+B)</td>
                <td><b>{{ num_all_patients }}</b></td>
            </tr>
        </table>

        <a class="btn btn-lg btn-default btn-main btn" href="{% url 'calcmain:dataimport' %}" role="button">Re-import data</a>
        <a class="btn btn-lg btn-info btn-main btn" id="loading" href="{% url 'calcmain:data_process' pk=study.pk %}" role="button">Confirm</a>
        <!-- <a class="btn btn-lg btn-info btn-main btn" id="extraprogress1" href="{% url 'calcmain:data_process' pk=study.pk %}" role="button">Confirm2</a> -->

    </div>

</div>

{% endblock %}

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/templates/calcmain/data_processed.html
{% extends 'calcmain/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">

    <div class="title text-center">
        <h1 class="title title-introduction">Processing the data</h1>

        {{data | safe}}

        <a class="btn btn-lg btn-default btn-processed" href="{% url 'calcmain:dataimport' %}" role="button">Re-import data</a>
        <a class="btn btn-lg btn-info btn-processed" id="loading" href="{% url 'calcmain:data_summary' pk=study.pk %}" role="button">Confirm</a>

    </div>

</div>

{% endblock %}

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/templates/calcmain/data_summary.html
{% extends 'calcmain/base.html' %}
{% load staticfiles %}

{% block content %}


<div class="container">

    <div class="title text-center">
        <h1 class="title title-introduction">Summary of the data</h1>
    </div>

    <div class="div-aligncenter div-centered">
        <table class="table table-hover table-summary">
            <tr>
                <td>Treatment</td>
                <td><b>{{ study.treatment_name }}</b></td>
            </tr>
            <tr>
                <td>Number of enrolled patients</td>
                <td><b>{{ num_all_patients }}</b></td>
            </tr>
            <tr>
                <td>Number of enrolled patients <br>having unequivocal radiologic progression, <br>symptomatic progression or death</td>
                <td><b>{{ study.up_patients }}</b></td>
            </tr>
        </table>

        <p class="graph-title" style="margin-top: 0%; margin-bottom: 0%;">Waterfall plot</p>
        {{ script | safe }}
        {{ div | safe }}
        <p class="graph-upmeaning" style="margin-left: 12%; margin-top: -2%;"><b>Distribution of the percent-change(%) of patients in imported data</b>
        <p class="graph-upmeaning" style="margin-left: 12%; font-size: 0.77em;">(Patients having unequivocal radiologic progression, symptomatic progression or death <b>are not included<b>)</p>

        <table class="table table-hover table-summary">
            <tr>
                <td>Proportion of patients who were diagnosed with partial response<br><b>(percent change ≤ -30%)</b></td>
                <td><b>{{ partial_response_prop }}%</b></td>
            </tr>
            <tr>
                <td>Proportion of patients who were diagnosed with progression<br><b>(percent change ≥ +20%, unequivocal, symptomatic progression  or death)</b></td>
                <td><b>{{ progression_prop }}%</b></td>
            </tr>
        </table>

        <div class="select-summary">
            <label for="sel-assumption">Which results do you want to confirm?</label>
            <select class="form-control" id="sel-assumption" name="sel-assumption" style="font-weight: bold">
                <option value="0" style="font-weight: bold">Please select an assumption.</option>
                <option value="1">Assumption 1. Same radiologist re-assesses tumor response.</option>
                <option value="2">Assumption 2. Another radiologist re-assesses tumor response.</option>
            </select>
        </div>

        <a class="btn btn-lg btn-default btn-processed" href="{% url 'calcmain:dataimport' %}" role="button">Re-import data</a>
        <button type="submit" class="btn btn-lg btn-info btn-processed" id="check_assumption">Calculate reproducibility of the results</button>
    </div>
</div>


<script language="javascript">
    document.getElementById('check_assumption').onclick = function() {
        var assumption = document.getElementById("sel-assumption").value;
        if(assumption == 0){
            alert("Please select an assumption.");
            document.getElementById("sel-assumption").focus();
        }else if(assumption == 1){
            document.location.href = "{% url 'calcmain:data_reassessment1' pk=study.pk %}";
            $.LoadingOverlay("show");
        }else if(assumption == 2){
            document.location.href = "{% url 'calcmain:data_reassessment2' pk=study.pk %}";
            $.LoadingOverlay("show");
        }
    }
</script>


{% endblock %}

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/templates/calcmain/final_result.html
{% extends 'calcmain/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">

    <div class="title text-center">
        <h1 class="title title-introduction">Calculation results</h1>
        <h4 class="sub-title">Treatment : <b>{{ study.treatment_name }}</b></h4>
    </div>

    <div class="div-aligncenter div-centered">

        <p class="graph-title">
        Distribution of proportion of patients who be diagnosed<br>with <span style="font-weight: bold; color: blue;">partial response (percent change ≤ 30%)</span>
        </p>
        {{ script_PR | safe }}
        {{ div_PR | safe }}
        <p class="graph-quantile" style="color: blue;"> 95% quantile: <b>{{ quantile_median_pr }}% [{{ quantile_bottom_pr }}%, {{ quantile_top_pr }}%] </b></p>
        <p class="graph-quantile" style="color: darkgray; margin-top: 0;"> 95% quantile: <b>Median [95% central range] </b></p>

        <p class="graph-title">
        Distribution of proportion of patients who be diagnosed<br>with <span style="font-weight: bold; color: red;">progression (percent change > 20%)</span>
        </p>
        {{ script_Pro | safe }}
        {{ div_Pro | safe }}
        <p class="graph-quantile" style="color: red;"> 95% quantile: <b>{{ quantile_median_pro }}% [{{ quantile_bottom_pro }}%, {{ quantile_top_pro }}%] </b></p>
        <p class="graph-quantile" style="color: darkgray; margin-top: 0;"> 95% quantile: <b>Median [95% central range] </b></p>

        <a class="btn btn-lg btn-default btn-processed" href="{% url 'calcmain:data_summary' pk=study.pk %}" role="button">Change assumption</a>
        <a class="btn btn-lg btn-info btn-processed" id="loading" href="{% url 'calcmain:export_delete' pk=study.pk%}" role="button">Finish and delete the data</a>
    </div>

</div>

{% endblock %}

django_basic/Semi_Project 5/프로젝트 예시 2. 엑셀 파일 처리 & Bokeh 그래프 시각화/calcmain/templates/calcmain/reassessment_result.html
{% extends 'calcmain/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">

    <div class="title text-center">
        <h1 class="title title-introduction">Reassessment results</h1>
        <h4 class="sub-title">Assumption {{ assumption_num }}. <b>{{ radiologist }} radiologist</b> re-assesses tumor response.</h4>
    </div>

    <div class="div-aligncenter div-centered">

        <p class="graph-title">Original distribution of patients in imported data</p>
        {{ script_summary | safe }}
        {{ div_summary | safe }}

        <p class="graph-title">Probability of diagnosis as <span style="font-weight: bold; color: blue;">partial response</span> when re-assessed</p>
        {{ script_PR | safe }}
        {{ div_PR | safe }}

        <p class="graph-uppatients" style="color: blue;"><b>n† = {{ up_patients }} (not considered to have measurement variability at repetition) </b></p>
        <p class="graph-upmeaning">† numbers of patients having probability 0 for partial response at the repetition <br>(unequivocal radiologic progression, symptomatic progression or death)</p>

        <p class="graph-title">Probability of diagnosis as <span style="font-weight: bold; color: red;">progression</span> when re-assessed</p>
        {{ script_Pro | safe }}
        {{ div_Pro | safe }}

        <p class="graph-uppatients"><b>n† = {{ up_patients }} (not considered to have measurement variability at repetition) </b></p>
        <p class="graph-upmeaning">† numbers of patients having probability 1 for progression at the repetition <br>(unequivocal radiologic progression, symptomatic progression or death)</p>


        <a class="btn btn-lg btn-default btn-processed" href="{% url 'calcmain:data_summary' pk=study.pk %}" role="button">Change assumption</a>
        <a class="btn btn-lg btn-info btn-processed" id="loading" href="{% url 'calcmain:final_result' pk=study.pk%}" role="button">Confirm</a>

    </div>
</div>

{% endblock %}